# Require the "Build" job to pass
status = [
    "Passed"
]

# Require 3 approvals
required_approvals = 3

# Delete branches after they're merged
delete_merged_branches = true

# Set the bors timeout to 20 minutes, after which it counts the build as failed
timeout_sec = 1200