name: Rust

on:
  push:
    branches: [ master, staging, trying ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Check code formatting with rustfmt
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        profile: minimal
        components: rustfmt
    
    - run: cargo +nightly fmt --all -- --check

  clippy:
    name: Lint with clippy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
        components: clippy
    - uses: actions/cache@v2.1.1
      with:
        path: |
          target
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
    - name: Install Linux dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev

    - run: cargo clippy

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    needs: [format, clippy]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
        components: clippy
    - uses: actions/cache@v2.1.1
      with:
        path: |
          target
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
    - name: Install Linux dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev
  
    - name: Build
      run: cargo build --verbose --workspace --all-targets

  test:
    name: Run test suite
    runs-on: ${{ matrix.os }}
    needs: [build]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
        components: clippy
    - uses: actions/cache@v2.1.1
      with:
        path: |
          target
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
    - name: Install Linux dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev
  
    - name: Test
      run: cargo test --verbose --workspace --all-targets


