name: Simple

on:
  push:
    branches: [ staging, trying ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  full-check:
    name: Check everything
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
        components: clippy
    - uses: actions/cache@v2.1.1
      with:
        path: |
          target
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
        key: ${{ runner.OS }}-simple-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.OS }}-simple

    - name: Install Linux dependencies
      if: ${{ runner.OS == 'Linux' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev libudev-dev
  
    - name: Build
      run: cargo build --verbose --workspace --all-targets --locked

    - name: Run clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --workspace --all-targets --all-features --locked -- D warnings

    - name: Test
      run: cargo test --verbose --workspace --all-targets --locked

  pass:
    name: Passed
    runs-on: ubuntu-latest
    needs: [full-check]
    steps:
    - run: exit 0
